.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2014 Alex <xenogenesi@virgilio.it>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FONT2C SECTION "June  4, 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
font2c \- Convert font to xbm (c header) using the freetype library
.SH SYNOPSIS
.B font2c
.RI [ font ]
.br
.\".SH DESCRIPTION"
.\"This manual page documents briefly the"
.\".B font2c"
.\"command."
.\".PP"
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
.\"\fBfont2c\fP is a program that..."
.SH OPTIONS
\fBfont\fP is full path font filename, the output will be on \fBstdout\fP.
.\".TP"
.\".B \-h, \-\-help"
.\"Show summary of options."
.\".TP"
.\".B \-v, \-\-version"
.\"Show version of program."
.\".SH SEE ALSO"
.\".BR baz (1)."
.\".br"
.\"The programs are documented fully by"
.\".IR "The Rise and Fall of a Fooish Bar" ,"
.\"available via the Info system."
